# This file is autogenerated from update.sh in the parent directory.
{
  dev = {
    version = "45.0.2431.0";
    sha256 = "0irlrym8r1wa6zb5bg4paxy3h5fg300k5c9vkj3xmhdp567clfja";
    sha256bin32 = "1lfrd7x7cav5mr7pg0a3d4a9dyy6f0rklarprfrcvqwipjkddb3f";
    sha256bin64 = "1jzmkgiqn17ynbv0xljiifvlj1136jq98zrkd4hdmkgv8xrrzd74";
  };
  beta = {
    version = "44.0.2403.61";
    sha256 = "16bifaqs3fmfms305c1h10kabsyrscxkywf32pl6zwlzjd3y4ncm";
    sha256bin32 = "1lgqf6bid02pjdzxg1jipfzjqzp5frqxv4bi6q127kky3lz9lmlc";
    sha256bin64 = "1l6cyfn5mraprisib7q5rgy8vvkc7ky8z91c2iqsikjv7nmrm6hv";
  };
  stable = {
    version = "43.0.2357.132";
    sha256 = "028qrvrhay02yw2lgprys6vqs1ds739grg1gjlvjj7czck354ps0";
    sha256bin32 = "1gfpxxhqd6v5b41hv6dq8nyickz2n03dxb742l20slr236iqvh7n";
    sha256bin64 = "1ahr78s7b53mxnpqhnfpig3rrc4dpkcg44p0zf0s171j5lzkwbdz";
  };
}
