# This file is autogenerated from update.sh in the parent directory.
{
  dev = {
    version = "43.0.2327.5";
    sha256 = "0k9jpzm1n7d3zv6f77vz33jcvmnbxnl6plabvlrf8w83kbzhi76n";
    sha256bin32 = "1dm4xp0x02kqj82giw45qd2z12wf22h2bs0d3hnlz050innxgcb6";
    sha256bin64 = "1b13g44y704llsnw68840zmaahj1hwzram50v8fqmff44w1b0bxb";
  };
  beta = {
    version = "42.0.2311.39";
    sha256 = "0qiyg8bg9f1daf8v2jlrv54lis7156h44ak42jdx96xanvj2rvj0";
    sha256bin32 = "0v4dr2a3n51dais2mg0dml0rmqfmalfj0zgp20a4kkarbpih1x0v";
    sha256bin64 = "19638ik9qgfmxpzdry0qwkwpzvhlbs2h2nn1kwsjja5j49817ksx";
  };
  stable = {
    version = "42.0.2311.90";
    sha256 = "1jdl1lq265rxw191cz44yb7ibdsk7qrvfw5fincwrl63q4wfpc30";
    sha256bin32 = "03bw3zqvb835c8nw9wzajb7m37ypyw03mn7kk3wky63irbvxdyy7";
    sha256bin64 = "1bawi8h09ha1283k4lwc5h7rg7bjpan4s45gqs6mixm0l6si41jd";
  };
}
